[package]
name = "runevis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netcdf = { version = "0.8.3", features = ["static"] }
rfd = "0.14.1"
iced = "0.12.1"